In [1]:
#korean tokenizer
from kobart import get_kobart_tokenizer
from transformers import BartTokenizer #안쓸수도 있음.
#kobart model
from kobart import get_pytorch_kobart_model
from transformers import BartModel
#other library
import pandas as pd
import numpy as np
import torch.nn as nn

#my file
from load_data import load_data,simple_preprocess

In [2]:
import pytorch_lightning

In [3]:
import torchtext

In [6]:
torchtext.__version__

'0.8.1'

In [2]:
#load data
#데이터는 약 6만개
sentence,abst = load_data('train_original.json')

In [105]:
frame = pd.DataFrame({"sentence" : sentence,"abstract" : abst})

In [109]:
frame.shape[0]

63067

In [122]:
frame.iloc[0]

sentence    이명박 대통령이 어제 30대 그룹 총수를 모아놓고 "시대적 요구는 역시 총수가 앞장...
abstract    이명박 대통령은 어제 30대 그룹 총수를 모아놓고 시대적 요구는 역시 총수가 앞장서...
Name: 0, dtype: object

In [4]:
sentence[0]

'이명박 대통령이 어제 30대 그룹 총수를 모아놓고 "시대적 요구는 역시 총수가 앞장서야 한다. 이미 상당한 변화의 조짐이 있다는 것을 고맙게 생각한다. 총수들께서 직접 관심을 가져주시면 빨리 전파돼 긍정적인 평가를 받을 수 있다고 본다"고 말했다.언뜻 보아 무슨 말인지 불분명하나 이 대통령이 지난 8ㆍ15 연설 후 정몽준 의원, 정몽구 현대차 회장이 각각 2000억원과 5000억원을 기부한 사실과 \'공생발전\'이란 화두를 연결하면 금방 짐작이 간다.다른 그룹 총수들도 좀 나서라고 은근히 떠민 것이다.이 대통령은 기부에 대한 후속 선언이 나오지 않은 탓인지 총수들의 사회공헌 방안에 불만을 표시했다는 후문이다.최근 미국 프랑스 벨기에 등에서 부유세가 거론되고 독일조차 2년간 한시적으로 5%의 자산세를 거둬 약 155조원을 마련하자는 논의가 있었다.이런 흐름에 한국만 동떨어져 있기는 어려운 게 글로벌 시대의 특징이다.항간에는 이번 회동 후 삼성을 비롯해 몇몇 그룹이 노블레스 오블리주 방안을 준비하고 있다는 말이 나도는데 대통령의 강요나 포퓰리즘에 의한 압박보다 자발적 문화로 만들어가야 효과가 큰 법이다.그런 면에서 재계에 적절한 방안 마련을 맡기고 정치권이나 여론은 너무 압박하지 말고 시간을 줘야 한다.국가채무 문제로 글로벌 경기 침체 우려가 큰 상황에서 기업들은 \'생존\'에 큰 부담을 느끼고 있기 때문이다.이날 전경련에 따르면 30대 그룹은 올해 고용 12만4000명, 투자 114조원 등 \'선물\'을 준비했다.세계적인 더블딥이 우려되는 상황에서 공격경영이 어렵겠지만 연초 한 번 발표한 내용을 약간 수정해 내놓은 전경련의 행태는 답답하다.설립 50주년이 됐으면 좀 더 창의적이고 유연하게 바뀔 때도 됐다.허창수 전경련 회장은 "대기업ㆍ중소기업이 서로 공생하고 발전할 수 있도록 노력하겠다. 기업이 사회적 책임을 다하겠다"는 원론적인 발언에 그쳐 전경련 특유의 무미건조함을 드러냈다.한편 이건희 삼성전자 회장은 "중소기업계 협력을 강화해 국제적으로 경쟁력 있는 기업

In [3]:
#Just ONE sentence
sample = simple_preprocess(sentence[0])
#view sample
print(sample[:100])

이명박 대통령이 어제 30대 그룹 총수를 모아놓고 시대적 요구는 역시 총수가 앞장서야 한다. 이미 상당한 변화의 조짐이 있다는 것을 고맙게 생각한다. 총수들께서 직접 관심을 가져주


구현단계
1. Tokenizer  
단순히 get_kobart_tokenizer.tokenize()만 사용하면 단어 id가 따로 출력되지는 않음.  
구해야 하는 값 : input_ids, attention_ids

In [5]:
from transformers import AutoTokenizer

In [8]:
tokenizer = get_kobart_tokenizer()

using cached model


In [9]:
tokenizer.tokenize(sample)

['▁이명박',
 '▁대통령이',
 '▁어제',
 '▁30대',
 '▁그룹',
 '▁총',
 '수를',
 '▁모아',
 '놓고',
 '▁시대',
 '적',
 '▁요구',
 '는',
 '▁역시',
 '▁총',
 '수가',
 '▁앞장',
 '서야',
 '▁한다.',
 '▁이미',
 '▁상당한',
 '▁변화의',
 '▁조짐',
 '이',
 '▁있다는',
 '▁것을',
 '▁고맙',
 '게',
 '▁생각한',
 '다.',
 '▁총',
 '수',
 '들',
 '께서',
 '▁직접',
 '▁관심을',
 '▁가져',
 '주시',
 '면',
 '▁빨리',
 '▁전파',
 '돼',
 '▁긍정적인',
 '▁평가를',
 '▁받을',
 '▁수',
 '▁있다고',
 '▁본',
 '다고',
 '▁말했다.',
 '언',
 '뜻',
 '▁보아',
 '▁무슨',
 '▁말',
 '인지',
 '▁불',
 '분',
 '명',
 '하나',
 '▁이',
 '▁대통령이',
 '▁지난',
 '▁8',
 'ᆞ',
 '15',
 '▁연설',
 '▁후',
 '▁정몽',
 '준',
 '▁의원',
 '▁정몽',
 '구',
 '▁현대차',
 '▁회장이',
 '▁각각',
 '▁2000',
 '억원',
 '과',
 '▁5000',
 '억원을',
 '▁기부',
 '한',
 '▁사실',
 '과',
 '▁공',
 '생',
 '발전',
 '이란',
 '▁화',
 '두를',
 '▁연결',
 '하면',
 '▁금방',
 '▁짐작',
 '이',
 '▁간',
 '다.',
 '다른',
 '▁그룹',
 '▁총',
 '수',
 '들도',
 '▁좀',
 '▁나서',
 '라고',
 '▁은',
 '근',
 '히',
 '▁떠',
 '민',
 '▁것이다.',
 '이',
 '▁대통령은',
 '▁기',
 '부에',
 '▁대한',
 '▁후속',
 '▁선언',
 '이',
 '▁나오지',
 '▁않은',
 '▁탓',
 '인지',
 '▁총',
 '수',
 '들의',
 '▁사회공헌',
 '▁방안에',
 '▁불만을',
 '▁표시',
 '했다는',
 '▁후문',


In [13]:
input_ids = tokenizer.encode(sample)

In [19]:
import torch
#add batch
input_ids = torch.tensor(input_ids)
input_ids_batch = input_ids.unsqueeze(0)

In [20]:
input_ids_batch.size()

torch.Size([1, 438])

In [50]:
seq_k = torch.tensor([1,2,3,4,5,6,7,8,0,0])
seq_k = seq_k.unsqueeze(0)
print(seq_k.size())

torch.Size([1, 10])


In [51]:
def get_attn_pad_mask(seq_q, seq_k):
    # print(seq_q)
    batch_size, len_q = seq_q.size()
    batch_size, len_k = seq_k.size()
    # eq(zero) is PAD token
    pad_attn_mask = seq_k.data.eq(0).unsqueeze(1)  # batch_size x 1 x len_k(=len_q), one is masking
    return pad_attn_mask.expand(batch_size, len_q, len_k)  # batch_size x len_q x len_k

In [52]:
result = get_attn_pad_mask(seq_k,seq_k)

In [53]:
result

tensor([[[False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True],
         [False, False, False, False, False, False, False, False,  True,  True]]])

In [54]:
result.shape

torch.Size([1, 10, 10])

function : masked_fill  
masked_fill함수는 조건을 만족하는 모든 값들을 다른 값으로 바꿔주는 함수라고 생각할 수 있음.  
아래 예시는 mask값이 1이면 원래 score를 -999로 바꾸는 예시.

In [69]:
seq_k.masked_fill(mask == 0,-9999)

tensor([[    1, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999],
        [    1,     2, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999],
        [    1,     2,     3, -9999, -9999, -9999, -9999, -9999, -9999, -9999],
        [    1,     2,     3,     4, -9999, -9999, -9999, -9999, -9999, -9999],
        [    1,     2,     3,     4,     5, -9999, -9999, -9999, -9999, -9999],
        [    1,     2,     3,     4,     5,     6, -9999, -9999, -9999, -9999],
        [    1,     2,     3,     4,     5,     6,     7, -9999, -9999, -9999],
        [    1,     2,     3,     4,     5,     6,     7,     8, -9999, -9999],
        [    1,     2,     3,     4,     5,     6,     7,     8,     0, -9999],
        [    1,     2,     3,     4,     5,     6,     7,     8,     0,     0]])

In [64]:
mask = torch.tril(torch.ones(10,10)).type(torch.BoolTensor)

In [7]:
#dataset
'''
dataset을 만들기 위해 구현해야할 것:
__init__ / __getitem__ / __len__

특히, __getitem__ 은 encoder_input_id, decoder_input_id,label_id 정보가 반드시 필요함.
encoder_input_id는 [1,2,3,4,5] 이런식 / 다른 정보도 마찬가지로 토큰화시키면 됨.
'''
from torch.utils.data import Dataset

class CustumDataset(Dataset):
    
    def __init__(self,file_name,tokenizer,max_len,pad_idx=None,ignore_idx = -999):
        self.tokenizer = tokenizer #토크나이저 설정
        self.max_len = max_len #sentence 최대길이 지정
        self.data = load_data(file_name) #데이터 불러오기
        self.len = self.data.shape[0] #데이터의 총 갯수
        self.pad_idx = pad_idx
        self.ignore_idx = ignore_idx
        
    def _add_padding2data(self,sentence):
        '''
        입력한 sequence가 max_len보다 작은 경우 padding을 진행해줌으로써 길이를 모두 동일하게 맞춰준다.
        반대로 sentence가 max_len보다 크거나 같은 경우, max_len만큼만 쓸 것이므로 잘라준다.
        '''
        if len(sentence) < self.max_len:
            pad_seq = np.array([self.pad_idx] * (self.max_len - len(sentence)))
            sentence = np.concatenate([sentence,pad_seq])
        else:
            sentence = sentence[:self.max_len]
        return sentence
    
    def _add_ignore2data(self,sentence):
        '''
        label(요약문)에 사용하는 함수로써 padding과 더불어 ignore_index를 추가해줌. 불필요한 길이를 방지하기 위함인거같음.(더 알아보기)
        '''
        if len(sentence) < self.max_len:
            pad_seq = np.array([self.ignore_idx] * (self.max_len - len(sentence)))
            sentence = np.concatenate([sentence,pad_seq])
        else:
            sentence = sentence[:self.max_len]
        return sentence
        
    def __getitem__(self,idx):
        #just for one line
        line = self.data.iloc[idx]
        sentence = line['sentence']
        abst = line['abstract']
        #encode : encoder input
        encoder_input_ids = self.tokenizer.encode_plus(sentence).input_ids
        encoder_input_ids = self._add_padding2data(encoder_input_ids)
        #encode : label (요약문)
        label_ids = self.tokenizer.encode_plus(abst).input_ids
        label_ids.append(self.tokenizer.eos_token_id)
        #encode : decoder input
        dec_input_ids = [self.tokenizer.eos_token_id]
        dec_input_ids += label_ids[:-1]
        dec_input_ids = self._add_padding2data(dec_input_ids)
        #add ignore_idx
        label_ids = self._add_ignore2data(label_ids)
        return {"encoder_input_ids" : encoder_input_ids ,
                "decoder_input_ids" : dec_input_ids,
                'label_ids' : label_ids}
    
    def __len__(self):
        return self.len

In [8]:
File_name = "train_original.json"
tokenizer = get_kobart_tokenizer()
max_len = 2048
pad_idx = 0
data = CustumDataset(file_name = File_name,tokenizer = tokenizer, max_len = max_len,pad_idx = pad_idx)

using cached model


In [13]:
data[1]

{'encoder_input_ids': array([16954, 15727, 14522, ...,     0,     0,     0]),
 'decoder_input_ids': array([    1, 15741, 11911, ...,     0,     0,     0]),
 'label_ids': array([15741, 11911, 11764, ...,  -999,  -999,  -999])}

In [14]:
from pytorch_lightning import loggers as pl_loggers

In [73]:
bart = BartModel.from_pretrained(get_pytorch_kobart_model())

using cached model


In [87]:
out = bart(seq_k)

In [79]:
output = bart(seq_k).last_hidden_state
print(output.size())

torch.Size([1, 10, 768])


In [78]:
linear = nn.Linear(768,128)

In [97]:
linear_output = linear(output)
print(linear_output.size())

torch.Size([1, 10, 128])


bart model의 output : last_hidden_state,past_key_values,encoder_last_hidden_state

In [98]:
linear_output

tensor([[[ 3.9937,  0.2334,  2.9882,  ...,  0.8528,  1.0862, -0.3879],
         [ 3.5808,  0.3890,  3.5731,  ..., -0.8300,  0.7109, -0.7916],
         [ 3.8944,  0.4965,  2.8769,  ...,  0.8735,  0.9011, -0.2143],
         ...,
         [ 2.4328,  0.9183,  1.0239,  ..., -1.0559,  1.7633,  0.1214],
         [ 1.6645,  0.3718,  0.0478,  ...,  0.0165,  1.2465,  0.6601],
         [ 2.3392,  1.1378,  1.0062,  ...,  1.4361,  0.3571, -0.0564]]],
       grad_fn=<AddBackward0>)

In [101]:
from transformers import BartForConditionalGeneration

In [102]:
bart_generation = BartForConditionalGeneration.from_pretrained(get_pytorch_kobart_model())

using cached model


In [ ]:
bart_generation